### ISSUE TITLE
stuck on self._intercomm.bcast(routing_table, root=MPI.ROOT)

### ISSUE THREAD

**Issue by TK-21st** [neurokernel/neurokernel#62]
as title.

Running with `managerless` on NK and `fbl` or `benchmark` on ND will stuck on https://github.com/neurokernel/neurokernel/blob/38c9ae3a9b6c96c4bb0915027249019411e8b9ba/neurokernel/mpi_proc.py#L300.

**Comment by yiyin** [comment]
I guess you are running managerless with the manager?

**Comment by TK-21st** [comment]
Need to change `mpi_relaunch` with the right network interface. 

Perhaps should add a message for that.
